
// for filtering data
export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST"
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS"
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE"


// for single product page
export const FETCH_SINGLE_PRODUCT_REQUEST="FETCH_SINGLE_PRODUCT_REQUEST"
export const FETCH_SINGLE_PRODUCT_SUCCESS="FETCH_SINGLE_PRODUCT_SUCCESS"
export const FETCH_SINGLE_PRODUCT_FAILURE="FETCH_SINGLE_PRODUCT_FAILURE" 



// add to cart action type
export const ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE="ADD_TO_CART_FAILURE"

