
// for filtering data
export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST"
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS"
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE"


// for single product page
export const FETCH_SINGLE_PRODUCT_REQUEST="FETCH_SINGLE_PRODUCT_REQUEST"
export const FETCH_SINGLE_PRODUCT_SUCCESS="FETCH_SINGLE_PRODUCT_SUCCESS"
export const FETCH_SINGLE_PRODUCT_FAILURE="FETCH_SINGLE_PRODUCT_FAILURE" 



// add to cart action type
export const ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE="ADD_TO_CART_FAILURE"



// to add product in cart in UI
export const FETCH_TO_CART_REQUEST="FETCH_TO_CART_REQUEST"
export const FETCH_TO_CART_SUCCESS="FETCH_TO_CART_SUCCESS"
export const FETCH_TO_CART_FAILURE="FETCH_TO_CART_FAILURE"

// remove from cart
export const REMOVE_FROM_CART_REQUEST="REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS="REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAILURE="REMOVE_FROM_CART_FAILURE"